site_name: Global Imagery Browse Services (GIBS)

nav:
    - 'index.md'
    - Available Visualizations: available-visualizations.md
    - Access Basics: access-basics.md
    - Access Advanced Topics: access-advanced-topics.md
    - Accessing via GIS Applications: gis-usage.md
    - Accessing via Map Libraries and Scripts: map-library-usage.md
extra_css:
    - css/style.css
extra_javascript:
    - javascript/overrides.js
theme:
    name: 'rtd-dropdown'
markdown_extensions:
    - admonition
    - attr_list
    - fenced_code
    - footnotes
