site_name: NASA GIBS

nav:
    - API Documentation: index.md
    - Available Imagery Products: about.md
    - Map Library Usage: map-library-usage.md
    - Geographic Information System (GIS) Usage: gis-usage.md
extra_css:
    - css/style.css
theme:
    name: cinder
