site_name: GIBS API for Developers

nav:
    - Available Visualizations: visualization-layers.md
    - Access Basics: visualization-services.md
    - Access Advanced Topics: api-advanced-topics.md
    - Accessing via GIS Applications: gis-usage.md
    - Accessing via GIS Libraries: map-library-usage.md
extra_css:
    - css/style.css
extra_javascript:
    - javascript/overrides.js
theme:
    name: 'rtd-dropdown'
markdown_extensions:
    - admonition
    - attr_list
    - fenced_code
