site_name: Global Imagery Browse Services (GIBS)

nav:
    - 'index.md'
    - Available Visualizations: visualization-layers.md
    - Available Imagery Products: available-imagery-products.md
    - Access Basics: visualization-services.md
    - Access Advanced Topics: api-advanced-topics.md
    - Accessing via GIS Applications: gis-usage.md
    - Accessing via Map Libraries and Scripts: map-library-usage.md
extra_css:
    - css/style.css
    - css/loading-spinner.css
extra_javascript:
    - https://cdn.jsdelivr.net/npm/vue@2
    - javascript/overrides.js
    - javascript/imagery-products.js
theme:
    name: 'rtd-dropdown'
markdown_extensions:
    - admonition
    - attr_list
    - fenced_code
    - footnotes
