site_name: NASA GIBS

nav:
    - GIBS API for Developers: index.md
    - Available Imagery Products: available-imagery.md
    - Map Library Usage: map-library-usage.md
    - Geographic Information System (GIS) Usage: gis-usage.md
extra_css:
    - css/style.css
extra_javascript:
    - javascript/overrides.js
theme:
    name: 'rtd-dropdown'
    
