site_name: Global Imagery Browse Services (GIBS)

nav:
    - 'index.md'
    - Available Visualizations: available-visualizations.md
    - Access Basics: access-basics.md
    - Access Advanced Topics: access-advanced-topics.md
    - Accessing via GIS Applications: gis-usage.md
    - Accessing via Map Libraries and GDAL Scripts: map-library-usage.md
    - Accessing via Python: python-examples/gibs-jupyter-notebook.ipynb
extra_css:
    - css/style.css
    - css/loading-spinner.css
extra_javascript:
    - javascript/vue@2.js
    - javascript/overrides.js
    - javascript/imagery-products.js
    - javascript/components.js
theme:
    name: 'rtd-dropdown'
markdown_extensions:
    - admonition
    - attr_list
    - fenced_code
    - footnotes
plugins:
    - mkdocs-jupyter
